-- CloudBase SQL schema for MVP analytics (PRD #16)

CREATE TABLE IF NOT EXISTS analytics_event_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_id VARCHAR(64) NULL,
  user_key VARCHAR(128) NOT NULL DEFAULT '',
  session_id VARCHAR(128) NOT NULL DEFAULT '',
  event_name VARCHAR(64) NOT NULL,
  event_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  page_name VARCHAR(64) NOT NULL DEFAULT '',
  generation_id VARCHAR(64) NOT NULL DEFAULT '',
  keywords_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  meaning_tag VARCHAR(32) NOT NULL DEFAULT '',
  style_tag VARCHAR(32) NOT NULL DEFAULT '',
  result_rank TINYINT UNSIGNED NULL,
  result_name VARCHAR(64) NOT NULL DEFAULT '',
  is_success TINYINT(1) NOT NULL DEFAULT 1,
  latency_ms INT UNSIGNED NULL,
  error_code VARCHAR(64) NOT NULL DEFAULT '',
  properties JSON NULL,
  _openid VARCHAR(64) DEFAULT '' NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_event_id (event_id),
  KEY idx_event_name_time (event_name, event_time),
  KEY idx_event_time (event_time),
  KEY idx_user_time (user_key, event_time),
  KEY idx_session_time (session_id, event_time),
  KEY idx_generation_id (generation_id),
  KEY idx_meaning_style (meaning_tag, style_tag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS analytics_generation_batch (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  generation_id VARCHAR(64) NOT NULL,
  user_key VARCHAR(128) NOT NULL DEFAULT '',
  session_id VARCHAR(128) NOT NULL DEFAULT '',
  keywords_text VARCHAR(255) NOT NULL DEFAULT '',
  keywords_json JSON NULL,
  keywords_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  meaning_tag VARCHAR(32) NOT NULL DEFAULT '',
  style_tag VARCHAR(32) NOT NULL DEFAULT '',
  requested_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  responded_at DATETIME(3) NULL,
  is_success TINYINT(1) NOT NULL DEFAULT 1,
  latency_ms INT UNSIGNED NULL,
  model_name VARCHAR(64) NOT NULL DEFAULT '',
  error_code VARCHAR(64) NOT NULL DEFAULT '',
  result_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  _openid VARCHAR(64) DEFAULT '' NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_generation_id (generation_id),
  KEY idx_requested_at (requested_at),
  KEY idx_user_requested (user_key, requested_at),
  KEY idx_success_requested (is_success, requested_at),
  KEY idx_meaning_style (meaning_tag, style_tag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS analytics_generation_result (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  generation_id VARCHAR(64) NOT NULL,
  result_rank TINYINT UNSIGNED NOT NULL,
  result_name VARCHAR(64) NOT NULL,
  meaning_title VARCHAR(128) NOT NULL DEFAULT '',
  meaning_desc VARCHAR(512) NOT NULL DEFAULT '',
  style_tags_json JSON NULL,
  copied_count INT UNSIGNED NOT NULL DEFAULT 0,
  favorited_count INT UNSIGNED NOT NULL DEFAULT 0,
  _openid VARCHAR(64) DEFAULT '' NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_generation_rank (generation_id, result_rank),
  KEY idx_result_name (result_name),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS analytics_metrics_daily (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  metric_date DATE NOT NULL,
  dimension_type VARCHAR(32) NOT NULL DEFAULT 'global',
  dimension_value VARCHAR(64) NOT NULL DEFAULT 'all',
  home_exposure_pv BIGINT UNSIGNED NOT NULL DEFAULT 0,
  click_generate_pv BIGINT UNSIGNED NOT NULL DEFAULT 0,
  generate_success_pv BIGINT UNSIGNED NOT NULL DEFAULT 0,
  result_page_dwell_avg_sec DECIMAL(10,2) NOT NULL DEFAULT 0,
  copy_pv BIGINT UNSIGNED NOT NULL DEFAULT 0,
  favorite_pv BIGINT UNSIGNED NOT NULL DEFAULT 0,
  regenerate_pv BIGINT UNSIGNED NOT NULL DEFAULT 0,
  second_generate_user_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  next_day_retained_user_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  day7_retained_user_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  favorite_return_user_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  _openid VARCHAR(64) DEFAULT '' NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_date_dimension (metric_date, dimension_type, dimension_value),
  KEY idx_metric_date (metric_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

